### PR TITLE
Multiple WordPress rulesets

### LINKED ISSUE #14: Multiple WordPress rulesets
The WordPress coding standards has a number of rulesets. Is there way to define which rulesets should be used?

### PR DESCRIPTION
**Pull request by chriszarate**
This fixes #14.

1. Updates [WordPress Coding Standards][1] to latest. With this PR, there is no longer a need to modify the rulesets to accommodate the path structure of the Brackets plugin. The rulesets are straight from the master branch of the repo.

2. Updates [PHPCS][2] to v2.3.3. Newer versions of PHPCS will look for a `CodeSniffer.conf` alongside the PHAR.

3. Adds a `CodeSniffer.conf` pointing to the "rulesets" subdirectory as an additional `installed_path`.

4. The relative path in `CodeSniffer.conf` can only be resolved if PHPCS is run from that directory (`{plugin_path}/modules/vendor/phpcs`). Therefore, this PR extends the plugin's use of Commander.js to accept an options hash, which can be passed to `child_process.exec`. A `buildOptions` method is added to the base class.

5. The PHPCS class overrides `buildOptions` to provide a `cwd` option, which `chdir`s the command to `{plugin_path}/modules/vendor/phpcs`. This allows the relative path to the local rulesets to be resolved.

6. Updates the settings HTML to add granular WPCS rulesets (WordPress-Core et al.).

7. Updates unit tests to provide options object. (To get tests to pass on my machine, I had to increase the `waitsFor` timeouts to 300+ ms. I didn't commit the change as it is probably just me.)

Tested on OS X, but not on Windows. However, care was taken to honor the existing Windows escaping patterns.

Thanks for a great plugin, hope this helps!

[1]: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
[2]: https://github.com/squizlabs/PHP_CodeSniffer

### CODE REVIEW

**Comment by mikaeljorhult** [comment]
Awesome! Thank you!

Will release a new version this weekend to include these changes.

**Comment by chriszarate** [comment]
Hi @mikaeljorhult! Was a new version ever released? I realized I'm still running my dev version, but when installing on a new machine I still got the old version.

**Comment by mikaeljorhult** [comment]
HI @chriszarate!
No, I ran into som CSS problems with the new releases of Brackets and haven't had any time to fix it, until last week. Just finished it up and pushed a new version.

**Comment by chriszarate** [comment]
Awesome! Great work, thanks!

**Pull request merged**
